#[derive(Debug, Clone, Copy)]
pub(crate) struct SearchParams {
    pub(crate) win_loss_utility_factor: f64,
    pub(crate) static_score_utility_factor: f64,
    pub(crate) dynamic_score_utility_factor: f64,
    pub(crate) dynamic_score_center_zero_weight: f64,
    pub(crate) dynamic_score_center_scale: f64,
    pub(crate) cpuct_exploration: f64,
    pub(crate) cpuct_exploration_log: f64,
    pub(crate) cpuct_exploration_base: f64,
    pub(crate) fpu_reduction_max: f64,
    pub(crate) root_fpu_reduction_max: f64,
    pub(crate) fpu_parent_weight_by_visited_policy_pow: f64,
    pub(crate) root_desired_per_child_visits_coeff: f64,
    pub(crate) value_weight_exponent: f64,
    pub(crate) chosen_move_temperature_early: f64,
    pub(crate) chosen_move_temperature: f64,
    pub(crate) chosen_move_temperature_halflife: f64,
    pub(crate) chosen_move_subtract: f64,
    pub(crate) chosen_move_prune: f64,
    pub(crate) root_noise_enabled: bool,
    pub(crate) root_dirichlet_noise_total_concentration: f64,
    pub(crate) root_dirichlet_noise_weight: f64,
    pub(crate) root_policy_temperature_early: f64,
    pub(crate) root_policy_temperature: f64,
    pub(crate) root_ending_bonus_points: f64,
    pub(crate) root_prune_useless_moves: bool,
    pub(crate) use_lcb_for_selection: bool,
    pub(crate) lcb_stdevs: f64,
    pub(crate) min_visit_prop_for_lcb: f64,
}

impl SearchParams {
    /// Values from KataGo's shipped `selfplay8mainb18.cfg`, including defaults
    /// from `Setup::loadParams` for fields omitted by that file.
    pub(crate) const KATAGO_SELFPLAY8_MAIN_B18: Self = Self {
        win_loss_utility_factor: 1.0,
        static_score_utility_factor: 0.05,
        dynamic_score_utility_factor: 0.30,
        dynamic_score_center_zero_weight: 0.25,
        dynamic_score_center_scale: 0.50,
        cpuct_exploration: 1.05,
        cpuct_exploration_log: 0.28,
        cpuct_exploration_base: 500.0,
        fpu_reduction_max: 0.2,
        root_fpu_reduction_max: 0.0,
        fpu_parent_weight_by_visited_policy_pow: 2.0,
        root_desired_per_child_visits_coeff: 2.0,
        value_weight_exponent: 0.5,
        chosen_move_temperature_early: 0.75,
        chosen_move_temperature: 0.15,
        chosen_move_temperature_halflife: 19.0,
        chosen_move_subtract: 0.0,
        chosen_move_prune: 1.0,
        root_noise_enabled: true,
        root_dirichlet_noise_total_concentration: 10.83,
        root_dirichlet_noise_weight: 0.25,
        root_policy_temperature_early: 1.5,
        root_policy_temperature: 1.1,
        root_ending_bonus_points: 0.5,
        root_prune_useless_moves: true,
        use_lcb_for_selection: true,
        lcb_stdevs: 5.0,
        min_visit_prop_for_lcb: 0.15,
    };
}
